# Generated by Django 3.1.1 on 2020-11-14 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porta_x', '0002_auto_20201109_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
