# Generated by Django 3.1.1 on 2020-11-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porta_z', '0003_color_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color_group',
            name='diagonal',
            field=models.PositiveIntegerField(),
        ),
    ]
