# Generated by Django 3.1.1 on 2020-11-14 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porta_z', '0004_auto_20201114_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dveri',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Color_group',
        ),
        migrations.DeleteModel(
            name='Dveri',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
