# Generated by Django 3.1.1 on 2020-11-14 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('porta_z', '0008_color_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color_group',
            old_name='id_col',
            new_name='id_col_gr',
        ),
        migrations.AlterField(
            model_name='color_group',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название группы цветов'),
        ),
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_color', models.PositiveIntegerField()),
                ('position', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255, verbose_name='Цвет')),
                ('color_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='porta_z.color_group', verbose_name='Группа цветов')),
            ],
        ),
    ]
