# Generated by Django 3.1.1 on 2020-11-14 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porta_z', '0010_someprod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SomeProd',
        ),
    ]
